services:
  web:
    image: php:8.1-apache
    container_name: mvc_apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./includes:/var/www/html/includes
      - ./src:/var/www/html/src
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mvc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
